# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - develop
    - master
    - /v\d*\.\d*\.\d*/

image: Visual Studio 2019
configuration: Release
platform: Any CPU
test: off

install:
  - cinst dotnetcore-sdk --version=3.1.101
  - choco install gitversion.portable

before_build:
  - gitversion /l console /output buildserver

build_script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release

artifacts:
  - path: bin\**\*.nupkg
    name: NuGet

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'