# http://www.appveyor.com/docs/appveyor-yml
branches:
  only:
    - develop
    - master
    - /v\d*\.\d*\.\d*/

image: Visual Studio 2019
test: off

build_script:
  - cmd: dotnet --info
  - cmd: build.cmd CI

artifacts:
  - path: \artifacts\*.*

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'