# http://www.appveyor.com/docs/appveyor-yml

version: 3.0.0.{build}
configuration: Release
image: Visual Studio 2017

build_script:
  - dotnet build
  - dotnet pack

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: Publish\**\*.nupkg
    name: NuGet

  - path: Publish\**\*.zip
    name: zip